trigger:
  branches:
    include:
      - main

pool:
  name: 'default'

steps:

- script: |
    git rev-parse --is-shallow-repository
    git fetch --unshallow
    git rev-parse --is-shallow-repository
    git remote add azure https://dev.azure.com/CLOUDORGANISATION/8CLD201_TP1/_git/8CLD201_TP1
    git push azure HEAD:main --force
    git remote remove azure || exit 0
  displayName: "Synchroniser GitHub main avec Azure DevOps main"