# deployment.yml
trigger:
- none  # à la suite de l'autre ?

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProjectId)'
    definition: '2'  
    artifactName: 'static-html-site'
    path: '$(Pipeline.Workspace)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'NomConnexionAzure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch -d '$web' -s "$(Pipeline.Workspace)/static-html-site/site-html.zip" --account-name "NomStockage"
